// Mock data for development and testing
// Use with MOCK_API=true environment variable
//
// Thresholds calibrated for FLY FISHING (not kayaking/rafting).
// Dual-mode rivers (Lower Sac, Trinity) include separate wade/drift statuses.

export const mockRivers = [
  {
    id: 'lower_sacramento',
    name: 'Lower Sacramento River',
    latitude: 40.59,
    longitude: -122.45,
    region: 'Shasta County',
    status: 'green',
    currentCfs: 5800,
    waterTempF: 54,
    trend: 'stable',
    trendContext: 'Stable — consistent conditions',
    cfsChange6hr: 80,
    statusReason: 'Optimal range for drift boat fishing.',
    riverType: 'tailwater',
    notes: 'Drift boat river — wade fishing not typical. Optimal 4,000–8,000 cfs. Blown out above ~12,000.',
    gaugeId: 'USGS 11370500',
    updatedAt: new Date().toISOString(),
    fishingModes: ['drift', 'wade'],
    thresholds: {
      greenFloor: 4000,
      greenCeiling: 8000,
      yellowFloor: 3000,
      yellowCeiling: 12000,
    },
    modeStatuses: [
      { mode: 'drift', status: 'green', statusReason: 'Optimal drift boat range.' },
      { mode: 'wade', status: 'yellow', statusReason: 'Wade fishing atypical — possible near banks below 5,000 cfs.' },
    ],
    blownOutCfs: 12000,
  },
  {
    id: 'upper_sacramento',
    name: 'Upper Sacramento River',
    latitude: 41.14,
    longitude: -122.36,
    region: 'Siskiyou County',
    status: 'green',
    currentCfs: 620,
    waterTempF: 50,
    trend: 'falling',
    trendContext: 'Falling — clearing, good for fishing',
    cfsChange6hr: -80,
    statusReason: 'Optimal range for fishing',
    riverType: 'freestone',
    notes: 'Optimal 400–800 cfs at Delta gauge. Wadeable below ~600. Blown out above 1,200.',
    gaugeId: 'USGS 11342000',
    updatedAt: new Date().toISOString(),
    fishingModes: ['wade'],
    thresholds: {
      greenFloor: 400,
      greenCeiling: 800,
      yellowFloor: 300,
      yellowCeiling: 1200,
    },
    blownOutCfs: 1200,
    dangerousWadeCfs: 600,
  },
  {
    id: 'mccloud',
    name: 'McCloud River',
    latitude: 41.07,
    longitude: -122.11,
    region: 'Shasta County',
    status: 'green',
    currentCfs: 850,
    waterTempF: 52,
    trend: 'stable',
    trendContext: 'Stable — consistent conditions',
    cfsChange6hr: 10,
    statusReason: 'Optimal range for fishing',
    riverType: 'spring-fed',
    notes: 'Optimal 800–1,200 cfs. Wadeable below ~900. Spring-fed, relatively stable.',
    gaugeId: 'USGS 11367500',
    updatedAt: new Date().toISOString(),
    fishingModes: ['wade'],
    thresholds: {
      greenFloor: 800,
      greenCeiling: 1200,
      yellowFloor: 600,
      yellowCeiling: 1500,
    },
    dangerousWadeCfs: 900,
  },
  {
    id: 'hat_creek',
    name: 'Hat Creek (Wild Trout)',
    latitude: 40.84,
    longitude: -121.51,
    region: 'Lassen County',
    status: 'green',
    currentCfs: 85,
    waterTempF: 55,
    trend: 'stable',
    trendContext: 'Stable — consistent conditions',
    cfsChange6hr: -2,
    statusReason: 'Optimal range for fishing',
    riverType: 'spring creek',
    notes: 'Spring creek, very low flows. Optimal 50–120 cfs. Wild Trout section below Powerhouse 2.',
    gaugeId: 'CDEC HTH',
    updatedAt: new Date().toISOString(),
    fishingModes: ['wade'],
    thresholds: {
      greenFloor: 50,
      greenCeiling: 120,
      yellowFloor: 30,
      yellowCeiling: 180,
    },
  },
  {
    id: 'fall_river',
    name: 'Fall River',
    latitude: 41.02,
    longitude: -121.44,
    region: 'Shasta County',
    status: 'green',
    currentCfs: 420,
    waterTempF: 54,
    trend: 'stable',
    trendContext: 'Stable — consistent conditions',
    cfsChange6hr: 5,
    statusReason: 'Optimal range for fishing',
    riverType: 'spring creek',
    notes: 'Spring-fed, very stable. Optimal 300–500 cfs. Boat/tube fishing only — no wading.',
    gaugeId: 'N/A',
    updatedAt: new Date().toISOString(),
    fishingModes: ['boat'],
    thresholds: {
      greenFloor: 300,
      greenCeiling: 500,
      yellowFloor: 200,
      yellowCeiling: 600,
    },
  },
  {
    id: 'pit_river',
    name: 'Pit River (Pit 3)',
    latitude: 41.04,
    longitude: -121.94,
    region: 'Shasta County',
    status: 'green',
    currentCfs: 350,
    waterTempF: 52,
    trend: 'stable',
    trendContext: 'Stable — consistent conditions',
    cfsChange6hr: 0,
    statusReason: 'Optimal range for fishing',
    riverType: 'dam-controlled',
    notes: 'Optimal 280–450 cfs (varies by section/powerhouse). Difficult wading — wading staff essential.',
    gaugeId: 'USGS 11359500',
    updatedAt: new Date().toISOString(),
    fishingModes: ['wade'],
    thresholds: {
      greenFloor: 280,
      greenCeiling: 450,
      yellowFloor: 200,
      yellowCeiling: 600,
    },
  },
  {
    id: 'trinity',
    name: 'Trinity River',
    latitude: 40.73,
    longitude: -122.81,
    region: 'Trinity County',
    status: 'red',
    currentCfs: 3420,
    waterTempF: 48,
    trend: 'rising',
    trendContext: 'Rising — may be muddying, fish may be off',
    cfsChange6hr: 1200,
    statusReason: 'Blown out — spring restoration pulse in progress.',
    riverType: 'tailwater',
    notes: 'Wade optimal 300–800 cfs. Drift boat 800–2,500 cfs. Spring restoration pulses can spike flows.',
    gaugeId: 'USGS 11525500',
    updatedAt: new Date().toISOString(),
    fishingModes: ['wade', 'drift'],
    thresholds: {
      greenFloor: 300,
      greenCeiling: 800,
      yellowFloor: 200,
      yellowCeiling: 1200,
    },
    modeStatuses: [
      { mode: 'wade', status: 'red', statusReason: 'Too high for wading — dangerous at 3,420 cfs.' },
      { mode: 'drift', status: 'yellow', statusReason: 'Above optimal drift boat range (800–2,500 cfs).' },
    ],
  },
  {
    id: 'truckee',
    name: 'Truckee River',
    latitude: 39.43,
    longitude: -120.03,
    region: 'Sierra Nevada',
    status: 'green',
    currentCfs: 250,
    waterTempF: 53,
    trend: 'stable',
    trendContext: 'Stable — consistent conditions',
    cfsChange6hr: 20,
    statusReason: 'Optimal range for fishing',
    riverType: 'dam-controlled',
    notes: 'Optimal 150–350 cfs for wading. Canyon section handles higher flows from a drift boat.',
    gaugeId: 'USGS 10346000',
    updatedAt: new Date().toISOString(),
    fishingModes: ['wade'],
    thresholds: {
      greenFloor: 150,
      greenCeiling: 350,
      yellowFloor: 100,
      yellowCeiling: 500,
    },
  },
  {
    id: 'little_truckee',
    name: 'Little Truckee River',
    latitude: 39.55,
    longitude: -120.16,
    region: 'Sierra Nevada',
    status: 'green',
    currentCfs: 100,
    waterTempF: 50,
    trend: 'stable',
    trendContext: 'Stable — consistent conditions',
    cfsChange6hr: -5,
    statusReason: 'Optimal range for fishing',
    riverType: 'tailwater',
    notes: 'Optimal 50–150 cfs. Tailwater below Stampede with consistent temps.',
    gaugeId: 'USGS 10340500',
    updatedAt: new Date().toISOString(),
    fishingModes: ['wade'],
    thresholds: {
      greenFloor: 50,
      greenCeiling: 150,
      yellowFloor: 30,
      yellowCeiling: 200,
    },
  },
  {
    id: 'east_walker',
    name: 'East Walker River',
    latitude: 38.33,
    longitude: -119.22,
    region: 'Mono County',
    status: 'green',
    currentCfs: 160,
    waterTempF: 51,
    trend: 'stable',
    trendContext: 'Stable — consistent conditions',
    cfsChange6hr: 5,
    statusReason: 'Optimal range for fishing',
    riverType: 'dam-controlled',
    notes: 'Miracle Mile. Optimal 100–225 cfs. Dangerous wading above 350 cfs.',
    gaugeId: 'USGS 10293000',
    updatedAt: new Date().toISOString(),
    fishingModes: ['wade'],
    thresholds: {
      greenFloor: 100,
      greenCeiling: 225,
      yellowFloor: 75,
      yellowCeiling: 350,
    },
    dangerousWadeCfs: 350,
  },
  {
    id: 'yuba',
    name: 'Yuba River',
    latitude: 39.57,
    longitude: -120.93,
    region: 'Nevada County',
    status: 'green',
    currentCfs: 550,
    waterTempF: 54,
    trend: 'falling',
    trendContext: 'Falling — clearing, good for fishing',
    cfsChange6hr: -60,
    statusReason: 'Optimal range for fishing',
    riverType: 'freestone',
    notes: 'Optimal 300–800 cfs for wading. Multiple forks — conditions vary.',
    gaugeId: 'USGS 11413000',
    updatedAt: new Date().toISOString(),
    fishingModes: ['wade'],
    thresholds: {
      greenFloor: 300,
      greenCeiling: 800,
      yellowFloor: 200,
      yellowCeiling: 1200,
    },
  },
  {
    id: 'north_fork_american',
    name: 'North Fork American River',
    latitude: 38.94,
    longitude: -120.73,
    region: 'Placer County',
    status: 'green',
    currentCfs: 750,
    waterTempF: 56,
    trend: 'stable',
    trendContext: 'Stable — consistent conditions',
    cfsChange6hr: 30,
    statusReason: 'Optimal range for fishing',
    riverType: 'freestone',
    notes: 'Optimal 500–1,000 cfs. Can run high during spring snowmelt.',
    gaugeId: 'USGS 11427000',
    updatedAt: new Date().toISOString(),
    fishingModes: ['wade'],
    thresholds: {
      greenFloor: 500,
      greenCeiling: 1000,
      yellowFloor: 350,
      yellowCeiling: 1500,
    },
  },
  {
    id: 'lower_owens',
    name: 'Lower Owens River',
    latitude: 37.39,
    longitude: -118.51,
    region: 'Inyo County',
    status: 'green',
    currentCfs: 165,
    waterTempF: 58,
    trend: 'falling',
    trendContext: 'Falling — clearing, good for fishing',
    cfsChange6hr: -25,
    statusReason: 'Optimal range for fishing',
    riverType: 'managed',
    notes: 'Wading dangerous above 300.',
    gaugeId: 'USGS 10251300',
    updatedAt: new Date().toISOString(),
    fishingModes: ['wade'],
    thresholds: {
      greenFloor: 80,
      greenCeiling: 280,
      yellowFloor: 50,
      yellowCeiling: 300,
    },
    dangerousWadeCfs: 300,
  },
  {
    id: 'hot_creek',
    name: 'Hot Creek',
    latitude: 37.66,
    longitude: -118.83,
    region: 'Mono County',
    status: 'green',
    currentCfs: 28,
    waterTempF: 62,
    trend: 'stable',
    trendContext: 'Stable — consistent conditions',
    cfsChange6hr: 1,
    statusReason: 'Optimal range for fishing',
    riverType: 'spring creek',
    notes: 'Tiny spring creek. Very technical. Fishable year-round.',
    gaugeId: 'USGS 10265150',
    updatedAt: new Date().toISOString(),
    fishingModes: ['wade'],
    thresholds: {
      greenFloor: 8,
      greenCeiling: 50,
      yellowFloor: 5,
      yellowCeiling: 70,
    },
  },
]

export const mockHistory = {
  lower_sacramento: [
    { timestamp: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(), cfs: 5600 },
    { timestamp: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(), cfs: 5700 },
    { timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(), cfs: 5750 },
    { timestamp: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(), cfs: 5800 },
    { timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(), cfs: 5850 },
    { timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(), cfs: 5820 },
    { timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), cfs: 5800 },
    { timestamp: new Date().toISOString(), cfs: 5800 },
  ],
  upper_sacramento: [
    { timestamp: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(), cfs: 750 },
    { timestamp: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(), cfs: 720 },
    { timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(), cfs: 700 },
    { timestamp: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(), cfs: 680 },
    { timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(), cfs: 660 },
    { timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(), cfs: 640 },
    { timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), cfs: 630 },
    { timestamp: new Date().toISOString(), cfs: 620 },
  ],
}
